### ISSUE TITLE
Add button to pause live graph

### ISSUE THREAD

**Issue by aka-Ani** [chillibasket/processing-grapher#18]
First of all, this is a really useful software and a brilliant piece of work! 

This is definitely not an "issue" but more of a feature/enhancement. In other serial plotters such as the Arduino built-in, a workaround for pausing the graphing was the disconnect the serial port. This allowed you to take a longer look at the graph or take a screenshot. I suppose the workaround here would be to record to a file and then load that file, but I think a pause/resume toggle for the live graph would be a handy feature.

**Comment by chillibasket** [comment]
Hi, it's great to hear you are putting my software to good use. Your suggestion to add a pause button sounds good and is probably a feature I would see myself using as well. Code contributions are always welcome and I am happy to merge the pull-request into the repo once I have tested the code and am sure it works as expected.

**Comment by chillibasket** [comment]
I have now added this feature in commit 414c8eb717f292466ad1719514e550938bcc6f01.  Please try out the latest version of the code in the Master branch and let me know if it is working as expected.

**Comment by aka-Ani** [comment]
I just tried this out, and the pause feature is working great! Thank you for adding it
