### ISSUE TITLE
Can't change colour of lines?

### ISSUE THREAD

**Issue by mksm1228** [chillibasket/processing-grapher#20]
![image](https://user-images.githubusercontent.com/54858715/117509091-7c1c6180-af3e-11eb-953e-3db240e6aa46.png)

When I click on the colour tags, I am unable to change the colours. I want the first one to be pink and the other one to be yellow...

**Comment by chillibasket** [comment]
Hi, currently it is not possible to manually change the colours of the tags. The colours are the same as the ones used on the graphs and are defined by [this line in the code](https://github.com/chillibasket/processing-grapher/blob/cce27ff93ebb5ae659da7625cdf0271a62d4aa44/ProcessingGrapher/ProcessingGrapher.pde#L88) which assigns a colour depending on the index number of the item:
`color[] c_colorlist = {c_blue, c_purple, c_red, c_yellow, c_green, c_orange};`

Custom colours for tags and graph signals is something I'm considering adding in the future. In the mean time you can easily change the values in the colorlist code above if you want to try out a different colour scheme.

**Comment by chillibasket** [comment]
This feature has now been added in program version 1.3.0 in commit 44b160124af1bd4ef9db273b41993158660623e8
