### ISSUE TITLE
Error: No processing.awt.PSurfaceAWT 

### ISSUE THREAD

**Issue by avongpa** [chillibasket/processing-grapher#27]
I found your software interesting and flexible to edit to my need (PID Controller GUI)
which i successed on Processing 3.5

unfortunately, Processing 4.0 complains about " processing.awt.PSurfaceAWT " library, 
My editing hasn't got me a workaround the issue. 
See below the exact error reporting. 
No library found for processing.awt.PSurfaceAWT
Libraries must be installed in a folder named 'libraries' inside the sketchbook folder (see the Preferences window).
The package “javafx” does not exist. You might be missing a library.

Secondly, just suggestion anyway, It will be nice if incorporate networking interface since we now have ethernet arduino shield. 
I will be glad if you can point to a direction. I wish to within my learning level improve on it.

**Comment by chillibasket** [comment]
Hi, it's great to hear that you are using and adapting the software. Unfortunately Processing 4 beta has not implemented all the core functionality which my code is using which used to be available in Processing 3; I'll look at porting the code over once the full version of Processing 4 comes out.

- The PSurface.AWT message is just a warning, and doesn't impact the functioning of the program.
- JavaFX is used as the renderer of the UI by default. If it isn't supported by Processing 4 yet you could try switching to a different renderer such as Java2d. See line 217 in ProcessingGrapher.pde
- I don't plan on adding any other networking options outside of serial to the program, but feel free to modify the code to add any functionality you need. Looking at Google there seem to be several forum thread discussing ethernet and processing: https://forum.arduino.cc/t/about-connecting-to-arduino-server-with-ethernet-through-processing/195088/17
