### ISSUE TITLE
Auto-scaling up and down

### ISSUE THREAD

**Issue by d-kozminihs** [chillibasket/processing-grapher#28]
At the moment it only scales to max value and remains there. I would like to have an option to auto-scale it back to lower peaks as older peaks scroll off the plot with time. This is standard behaviour of Arduino IDE plotter and works better in some cases.

**Comment by chillibasket** [comment]
This feature has been added in v1.3.4 (commit fab5baf1b870baf813e67bed3fb3ebfa82e4a012). You can now switch between the three different graph scaling modes  (Manual, Expand Only, Full Auto) using the same button in the sidebar.
