### ISSUE TITLE
Plotting two variables on XY axes

### ISSUE THREAD

**Issue by d-kozminihs** [chillibasket/processing-grapher#29]
Plotting two variables on XY axes instead of time-scale. Maybe this is something relatively easy to implement, but I couldn’t figure out yet. It might be handy to place it on an additional tab between "Live Graph" and "File Graph". I could image few scenarios where both plots could supplement each other.

**Comment by pedroavex** [comment]
Adding myself here to get updates, as this is also my interest. Thanks.

**Comment by chillibasket** [comment]
This feature has now been added in commit 6a98a8177b82a66bbaa69cbfa2f139540ba9d176. A signal in the "Live Graph" tab can be used as the x-axis by clicking on the "^" when a signal is on Graph 1 in the right-hand sidebar. Let me know if you come across any issues when using this feature.
