### ISSUE TITLE
Connect button in Live Graph tab

### ISSUE THREAD

**Issue by RosscoG** [chillibasket/processing-grapher#36]
It would be useful (to me) to have a button for disconnecting/reconnecting in the Live Graph tab.  I am interested if this would be useful for others?  What is 'normal' use of processing-grapher?

I generally have the Live Graph tab open on one monitor and want to disconnect in a single click, keeping it all ready to reconnect.  
I've hacked it in and it greatly improved workflow.  I slotted it in after `Start Recording` (instead of your next heading, sorry), worked well enough for a hack.
![image](https://user-images.githubusercontent.com/2402803/236970878-dc9eaaae-af5e-42e6-8b6f-2778f707410c.png)

Thank you @chillibasket for this excellent tool!  I have been using it every day solid for a week on my current project.
I grabbed it out of frustration with other serial monitoring methods and have hacked in anything I wanted as I went.  All I do now is push data for immediate feedback, sticking any error or status msg etc wherever I like. Love it.

**Comment by chillibasket** [comment]
Hi, it's great to hear that you are finding the program useful! I don't often hear how other people are using the program so am not sure about a 'normal' use. In the past I used the graphs a lot but recently I'm mainly using the serial monitor; I guess it really depends on what you are working on... 

One option I was thinking about in the past was to put an icon onto the bottom status bar (to the right of the file location text) which shows the connection status. If the user presses on this it could connect/disconnect the serial port.

**Comment by chillibasket** [comment]
This feature has now been included in release v1.6.0 d55b798
