### ISSUE TITLE
The package “javafx” does not exist. You might be missing a library.

### ISSUE THREAD

**Issue by ajk1982** [chillibasket/processing-grapher#37]
<img width="212" alt="Screenshot 2023-10-02 at 18 20 09" src="https://github.com/chillibasket/processing-grapher/assets/1137677/d4c76787-bb9c-4d02-9ba6-0756cc645a25">

Hi, new to processing. I cannot figure out the error I get when trying to run processing-grapher. I get the error The package “javafx” does not exist. You might be missing a library.

As far as I can see I have the library. Can you help at all?
Thanks

**Comment by chillibasket** [comment]
The ProcessingGrapher program is currently not supported in the newest version of Processing, since the new version does not support JavaFx in the same way as the old version used to. 

Make sure you are using Processing IDE version 3.5.4

**Comment by ajk1982** [comment]
Maybe I should have read the installation guide more carefully! 

Thanks for your help, I will try it tomorrow.
