### ISSUE TITLE
Record Graph Data to .CSV more than 100000 rows error

### ISSUE THREAD

**Issue by LEESY97** [chillibasket/processing-grapher#38]
First of all, thank you for the useful program!
The following problem occurred while using the program. Please understand that my English is not good, so the explanation may be strange.

I use this program Version 1.5.0 with processing 3.5.4
I want to save more than 100000 rows of data coming in through serial communication.
When saving as a txt file using Record Messages, a new file is created and saved when it exceeds 50000 rows.
However, when saving as a csv file using Record Graph Data, the following window appears after saving up to 100000 rows and does not work properly.
Could it be that I made a mistake while using it?

![image (8)](https://github.com/chillibasket/processing-grapher/assets/77132877/9c78fa9e-422a-4e11-b6db-0f1548fe193f)
![image (9)](https://github.com/chillibasket/processing-grapher/assets/77132877/13da9ff5-6343-44f7-8d91-fc5fbd553319)
![image (10)](https://github.com/chillibasket/processing-grapher/assets/77132877/c644192c-a06b-4b6d-b0a4-3aaa08573267)

**Comment by chillibasket** [comment]
You are using the program correctly. 

If an error occurs while the program is trying to save new data to the file, it will try to create a new file with "-backup" in the name to save the data and prevent it from being lost. What is happening is that for some reason, the data saving is failing multiple times while you are recording, and each time it creates a new file with another "-backup" in the name. 

I've found that file saving can sometimes fail if you are saving to a USB flash driver, or to a network location which is not on your computer. If this is not the reason in your case, I would need to do some more tests with large data files. I don't think files that big are created very often, so you may be the first person to use it in this application.

**Comment by LEESY97** [comment]
Thank you for your answer.

I tried saving to two locations:
1. C:\processing
2. C:\Users\UserK\Desktop

but all of them error occurs.
![image](https://github.com/chillibasket/processing-grapher/assets/77132877/b912262c-8b2e-4eb1-a21d-066957e60c2f)

and Live Graph is stop.
![image](https://github.com/chillibasket/processing-grapher/assets/77132877/a89032a5-8928-467c-bf60-83f439666399)

**Comment by chillibasket** [comment]
This issue should now be fixed in release version v1.6.0 d55b798
